class AppStrings{

  static String appName = "Doctor App",
   bestDocApp = "Best Doctor\n Appointment App",
   welcomeBack = "Welcome Back!",
   weAreExcited = "We're excited to have you back!",
   signupNow = "Sign up now and start exploring all that our app has to offer.",
   email = "Email",
   emailHint = "Enter your email",
   password = "Password",
   passwordHint = "Enter your password here...",
   fullname = "Full Name",
   fullnameHint = "Enter your name here...",
   confirmPassword = "Confirm Password",
   forgetPassword = "Forget Password?",
   welcome= "Welcome",
   login = "Login",
   signup = "Signup",
   alreadyHaveAccount = "Account have an account?",
   dontHaveAccount = "Don't have an account?",
   body="Body",
   ear = "Ear",
  eye = "Eye",
  setting = "Setting",
  category = "Category",
  doctor = "Doctor",
  kidney = "Kidney",
  lungs = "Lungs",
  stomach = "Stomach",
  changePassword = "Change Password",
  termsCondition = "Terms & Condition",
  aboutUs = 'About US',
  signOut = "SignOut",
  teeth = "Teeth";

}

